using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WeatherEvents.Models;

public class WeatherEvent
{
    [Key] // Primary key
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public long Id { get; set; } // Auto-generated by SQL Server
    public string StationId { get; set; } = string.Empty;

    public DateTime Timestamp { get; set; }

    public decimal Temperature { get; set; }

    public decimal Humidity { get; set; }

    public decimal Pressure { get; set; }

    public decimal WindSpeed { get; set; }

    public string SequenceNumber { get; set; } = string.Empty;// Provided by the weather station
}
